//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyCuaHangQuanAoEntities1 : DbContext
    {
        public QuanLyCuaHangQuanAoEntities1()
            : base("name=QuanLyCuaHangQuanAoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DbSet<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuNhapHang> PhieuNhapHangs { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    
        [DbFunction("QuanLyCuaHangQuanAoEntities1", "fn_ChiTietSanPhamHoaDon")]
        public virtual IQueryable<fn_ChiTietSanPhamHoaDon_Result> fn_ChiTietSanPhamHoaDon(Nullable<int> maHoaDon)
        {
            var maHoaDonParameter = maHoaDon.HasValue ?
                new ObjectParameter("MaHoaDon", maHoaDon) :
                new ObjectParameter("MaHoaDon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ChiTietSanPhamHoaDon_Result>("[QuanLyCuaHangQuanAoEntities1].[fn_ChiTietSanPhamHoaDon](@MaHoaDon)", maHoaDonParameter);
        }
    
        [DbFunction("QuanLyCuaHangQuanAoEntities1", "fn_DanhSachNhanVien_TrangThai")]
        public virtual IQueryable<fn_DanhSachNhanVien_TrangThai_Result> fn_DanhSachNhanVien_TrangThai(string trangThai)
        {
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("trangThai", trangThai) :
                new ObjectParameter("trangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_DanhSachNhanVien_TrangThai_Result>("[QuanLyCuaHangQuanAoEntities1].[fn_DanhSachNhanVien_TrangThai](@trangThai)", trangThaiParameter);
        }
    
        [DbFunction("QuanLyCuaHangQuanAoEntities1", "fn_LayDanhSachSPBoiLoai")]
        public virtual IQueryable<fn_LayDanhSachSPBoiLoai_Result> fn_LayDanhSachSPBoiLoai(Nullable<int> maLoai)
        {
            var maLoaiParameter = maLoai.HasValue ?
                new ObjectParameter("maLoai", maLoai) :
                new ObjectParameter("maLoai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_LayDanhSachSPBoiLoai_Result>("[QuanLyCuaHangQuanAoEntities1].[fn_LayDanhSachSPBoiLoai](@maLoai)", maLoaiParameter);
        }
    
        [DbFunction("QuanLyCuaHangQuanAoEntities1", "fn_LocTheoYeuCau")]
        public virtual IQueryable<fn_LocTheoYeuCau_Result> fn_LocTheoYeuCau(Nullable<int> maLoai, Nullable<decimal> minPrice, Nullable<decimal> maxPrice)
        {
            var maLoaiParameter = maLoai.HasValue ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(int));
    
            var minPriceParameter = minPrice.HasValue ?
                new ObjectParameter("MinPrice", minPrice) :
                new ObjectParameter("MinPrice", typeof(decimal));
    
            var maxPriceParameter = maxPrice.HasValue ?
                new ObjectParameter("MaxPrice", maxPrice) :
                new ObjectParameter("MaxPrice", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_LocTheoYeuCau_Result>("[QuanLyCuaHangQuanAoEntities1].[fn_LocTheoYeuCau](@MaLoai, @MinPrice, @MaxPrice)", maLoaiParameter, minPriceParameter, maxPriceParameter);
        }
    
        [DbFunction("QuanLyCuaHangQuanAoEntities1", "fn_SanPhamTonKhoDuoi10")]
        public virtual IQueryable<fn_SanPhamTonKhoDuoi10_Result> fn_SanPhamTonKhoDuoi10()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_SanPhamTonKhoDuoi10_Result>("[QuanLyCuaHangQuanAoEntities1].[fn_SanPhamTonKhoDuoi10]()");
        }
    
        [DbFunction("QuanLyCuaHangQuanAoEntities1", "fn_TimKiemKhachHang")]
        public virtual IQueryable<fn_TimKiemKhachHang_Result> fn_TimKiemKhachHang(string hoTen, string diaChi)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiemKhachHang_Result>("[QuanLyCuaHangQuanAoEntities1].[fn_TimKiemKhachHang](@HoTen, @DiaChi)", hoTenParameter, diaChiParameter);
        }
    
        [DbFunction("QuanLyCuaHangQuanAoEntities1", "GetThongTinKhachHang")]
        public virtual IQueryable<GetThongTinKhachHang_Result> GetThongTinKhachHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetThongTinKhachHang_Result>("[QuanLyCuaHangQuanAoEntities1].[GetThongTinKhachHang]()");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
