//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ChiTietHoaDon_SanPham
    {
        public Nullable<int> MaHoaDon { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MauSac { get; set; }
        public string Size { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    }
}
